// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGOzIzsujQLOXxfEMv8wII_bS42Do6Bl4',
    appId: '1:403962643959:web:13b813c3f4d1a1cbe45af2',
    messagingSenderId: '403962643959',
    projectId: 'test2-b5ea9',
    authDomain: 'test2-b5ea9.firebaseapp.com',
    storageBucket: 'test2-b5ea9.appspot.com',
    measurementId: 'G-QH9C3WQD1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9kqRab9o7DJXeassES6AVdXr8ttLNGK0',
    appId: '1:403962643959:android:90fbb1271941063fe45af2',
    messagingSenderId: '403962643959',
    projectId: 'test2-b5ea9',
    storageBucket: 'test2-b5ea9.appspot.com',
  );
}
